version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: ecommerce-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

volumes:
  mysql_data: