spring.application.name=stealdeals
spring.web.resources.static-locations=classpath:/static/

# SERVER
server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# GOOGLE
google.client-id=${GOOGLE_CLIENT_ID}

# REDIS
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}

# TWILIO
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

# MAIL
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RAZORPAY
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
razorpay.plan_id=${RAZORPAY_PLAN_ID}
razorpay.webhook_secret=${RAZORPAY_WEBHOOK_SECRET}

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB